export const GEAR_TAXONOMY = {
  brands: [
    "Akai",
    "Arturia",
    "Behringer",
    "Casio",
    "Clavia",
    "Dave Smith Instruments",
    "Elektron",
    "E-mu",
    "Ensoniq",
    "Intellijel",
    "Korg",
    "Make Noise",
    "Moog",
    "Mutable Instruments",
    "Novation",
    "Oberheim",
    "Roland",
    "Sequential",
    "Sequential Circuits",
    "Teenage Engineering",
    "Waldorf",
    "Yamaha",
  ],
  categories: [
    "synth",
    "drum-machine",
    "sampler",
    "sequencer",
    "groovebox",
    "effects",
    "modular",
    "mixer",
    "audio-interface",
    "keyboard-controller",
    "rack-synth",
  ],
  aliases: {
    "Juno106": "Juno-106",
    "Juno 106": "Juno-106",
    "Juno-106": "Juno-106",
    "TR909": "TR-909",
    "TR 909": "TR-909",
    "TR-909": "TR-909",
    "TB303": "TB-303",
    "TB 303": "TB-303",
    "TB-303": "TB-303",
    "DX7": "DX7",
    "SP1200": "SP-1200",
    "SP 1200": "SP-1200",
    "SH101": "SH-101",
    "SH 101": "SH-101",
    "SH-101": "SH-101",
    "JX3P": "JX-3P",
    "JX 3P": "JX-3P",
    "JX-3P": "JX-3P",
    "TG33": "TG-33",
    "TG 33": "TG-33",
    "TG-33": "TG-33",
    "R8": "R-8",
    "R 8": "R-8",
    "R-8": "R-8",
  },
  categoryTerms: {
    synth: ["synth", "synthesizer", "シンセ", "シンセサイザー", "keyboard"],
    "drum-machine": ["drum machine", "rhythm machine", "drumcomputer", "ドラムマシン", "リズムマシン", "リズムボックス"],
    sampler: ["sampler", "sampling", "サンプラー"],
    sequencer: ["sequencer", "シーケンサー"],
    groovebox: ["groovebox", "groove box", "グルーブボックス", "グルーヴボックス"],
    effects: ["effect", "effects", "pedal", "エフェクター"],
    modular: ["eurorack", "modular", "module", "モジュラー", "ユーロラック"],
    mixer: ["mixer", "mixing console", "ミキサー"],
    "audio-interface": ["audio interface", "interface", "オーディオインターフェイス"],
    "keyboard-controller": ["midi controller", "keyboard controller", "controller"],
    "rack-synth": ["rack", "sound module", "音源モジュール"],
  },
  noiseTerms: [
    "book",
    "catalog",
    "cd",
    "comic",
    "dvd",
    "manual",
    "magazine",
    "record",
    "sticker",
    "vinyl",
    "カタログ",
    "コミック",
    "ステッカー",
    "マニュアル",
    "レコード",
    "取扱説明書",
  ],
};
