export const SOURCE_ACCESS_TYPES = {
  API: "api",
  SCRAPE: "scrape",
  BROWSER_ASSISTED: "browser-assisted",
  MANUAL: "manual",
  SEARCH_URL: "search-url",
};

export const SOURCE_STATUSES = {
  ACTIVE: "active",
  TESTING: "testing",
  BROKEN: "broken",
  PAUSED: "paused",
  CANDIDATE: "candidate",
};

export const SOURCE_REGISTRY = [
  {
    id: "mercari",
    name: "Mercari Japan",
    slug: "mercari-japan",
    regionId: "japan",
    url: "https://jp.mercari.com",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.BROWSER_ASSISTED,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 72,
    noiseScore: 55,
    testQuery: "Roland Juno 106",
    notes: "High value Japan source; browser automation is slower but currently useful.",
  },
  {
    id: "yahoo-auctions",
    name: "Yahoo Auctions Japan",
    slug: "yahoo-auctions-japan",
    regionId: "japan",
    url: "https://auctions.yahoo.co.jp",
    type: "auction",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 84,
    noiseScore: 45,
    testQuery: "Waldorf",
    notes: "Core Japan auction source.",
  },
  {
    id: "yahoo-fleamarket",
    name: "Yahoo Fleamarket",
    slug: "yahoo-fleamarket",
    regionId: "japan",
    url: "https://paypayfleamarket.yahoo.co.jp",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 78,
    noiseScore: 50,
    testQuery: "Waldorf",
    notes: "Useful Japan marketplace source with occasional noise.",
  },
  {
    id: "rakuma",
    name: "Rakuma",
    slug: "rakuma",
    regionId: "japan",
    url: "https://fril.jp",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 60,
    testQuery: "Waldorf",
    notes: "Useful but can be noisy and thumbnail handling requires proxy support.",
  },
  {
    id: "digimart",
    name: "Digimart",
    slug: "digimart",
    regionId: "japan",
    url: "https://www.digimart.net",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 88,
    noiseScore: 20,
    testQuery: "Sequential Circuits",
    notes: "High signal Japan music gear source.",
  },
  {
    id: "jimoty",
    name: "Jimoty",
    slug: "jimoty",
    regionId: "japan",
    url: "https://jmty.jp/all/sale-inc",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 62,
    noiseScore: 68,
    testQuery: "シンセサイザー",
    notes: "Local classifieds source; likely noisy but useful for local finds.",
  },
  {
    id: "offmall",
    name: "OFFMALL / Hard Off",
    slug: "offmall-hard-off",
    regionId: "japan",
    url: "https://netmall.hardoff.co.jp",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 82,
    noiseScore: 25,
    testQuery: "Roland",
    notes: "Strong used gear network source.",
  },
  {
    id: "five-g",
    name: "Five G",
    slug: "five-g",
    regionId: "japan",
    url: "https://fiveg.net",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 12,
    testQuery: "Oberheim",
    notes: "Low volume but high signal specialist shop.",
  },
  {
    id: "implant4",
    name: "implant4",
    slug: "implant4",
    regionId: "japan",
    url: "https://shop.implant4.com",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 12,
    testQuery: "Oberheim",
    notes: "Low volume but high signal specialist shop.",
  },
  {
    id: "reverb",
    name: "Reverb Japan",
    slug: "reverb-japan",
    regionId: "japan",
    url: "https://reverb.com",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 86,
    noiseScore: 22,
    testQuery: "Oberheim",
    notes: "Currently queried with Japan country filter.",
  },
  {
    id: "reverb-us",
    name: "Reverb US",
    slug: "reverb-us",
    regionId: "bay-area",
    url: "https://reverb.com/marketplace?query=synth",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 86,
    noiseScore: 25,
    testQuery: "synth",
    notes: "Live beta US connector for Bay Area, Los Angeles, and East Coast. Broad US/global inventory, filtered by Brrtz Gear Mode.",
  },
  {
    id: "ebay-us",
    name: "eBay US",
    slug: "ebay-us",
    regionId: "bay-area",
    url: "https://www.ebay.com/sch/i.html?_nkw=synthesizer",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 78,
    noiseScore: 60,
    testQuery: "synthesizer",
    notes: "Official Browse API connector live in Bay Area, Los Angeles, and East Coast beta. Defaults to eBay category 619; requires EBAY_CLIENT_ID and EBAY_CLIENT_SECRET.",
  },
  {
    id: "guitar-center-used",
    name: "Guitar Center Used",
    slug: "guitar-center-used",
    regionId: "bay-area",
    url: "https://www.guitarcenter.com/Used/Synthesizers-Sound-Modules.gc",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 55,
    noiseScore: 25,
    testQuery: "drum machine",
    notes: "Beta manual assist. Direct server fetch returned access denial and robots.txt disallows broad search paths; open relevant used category links in the user browser instead.",
  },
  {
    id: "sweetwater-used",
    name: "Sweetwater Used / Gear Exchange",
    slug: "sweetwater-used",
    regionId: "bay-area",
    url: "https://www.sweetwater.com/used/listings",
    type: "marketplace-used",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 62,
    noiseScore: 22,
    testQuery: "drum machine",
    notes: "Beta manual assist. Sweetwater is music-gear-specific, but server-side requests hit PerimeterX/403 during scout; open prepared used-gear searches in the user browser instead.",
  },
  {
    id: "craigslist-sfbay",
    name: "Craigslist SF Bay Area",
    slug: "craigslist-sfbay",
    regionId: "bay-area",
    url: "https://sfbay.craigslist.org/search/msa?query=synth",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.PAUSED,
    reliabilityScore: 60,
    noiseScore: 45,
    testQuery: "synth",
    notes: "Parked for beta safety after Craigslist blocking. Manual/search-link first until a safe access path is confirmed.",
  },

  {
    id: "craigslist-la",
    name: "Craigslist Los Angeles",
    slug: "craigslist-la",
    regionId: "los-angeles",
    url: "https://losangeles.craigslist.org/search/msa?query=synth",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.PAUSED,
    reliabilityScore: 62,
    noiseScore: 45,
    testQuery: "synth",
    notes: "Parked for beta safety after Craigslist blocking. Keep as manual/search-link first until a safe access path is confirmed.",
  },
  {
    id: "craigslist-east",
    name: "Craigslist East Coast",
    slug: "craigslist-east-coast",
    regionId: "east-coast",
    url: "https://newyork.craigslist.org/search/msa?query=synth",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.PAUSED,
    reliabilityScore: 62,
    noiseScore: 45,
    testQuery: "synth",
    notes: "Parked for beta safety. Aggregates NYC, New Jersey, Long Island, Hudson Valley, Boston, Philadelphia, DC, and Baltimore when Craigslist live mode is enabled.",
  },
  {
    id: "main-drag",
    name: "Main Drag Music",
    slug: "main-drag-music",
    regionId: "east-coast",
    url: "https://maindragmusic.com/collections/keyboard",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 66,
    noiseScore: 22,
    testQuery: "synth",
    notes: "Brooklyn independent shop with keyboard, synth, rhythm, modular, and vintage/used categories. Live HTML parser returns product cards from shop search.",
  },
  {
    id: "rogue-music",
    name: "Rogue Music",
    slug: "rogue-music",
    regionId: "east-coast",
    url: "https://www.roguemusic.com/",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 64,
    noiseScore: 18,
    testQuery: "synth",
    notes: "NYC used/vintage gear institution with keys, synths, samplers, drum machines, sequencers, and pro audio categories. Live POST-backed HTML parser returns product cards.",
  },
  {
    id: "three-wave",
    name: "Three Wave Music",
    slug: "three-wave-music",
    regionId: "east-coast",
    url: "https://threewavemusic.com/",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 72,
    noiseScore: 12,
    testQuery: "synth",
    notes: "New, used, and vintage keyboard/synth specialist in Midland Park, NJ. Live BigCommerce parser returns product cards.",
  },
  {
    id: "alto-music",
    name: "Alto Music",
    slug: "alto-music",
    regionId: "east-coast",
    url: "https://www.altomusic.com/search?q=synth",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 64,
    noiseScore: 32,
    testQuery: "synth",
    notes: "NY-based musical instrument and pro-audio retailer with substantial used/open-box inventory. Live Shopify parser returns product cards; pricing is enriched from product JSON where possible.",
  },
  {
    id: "tone-tweakers",
    name: "Tone Tweakers",
    slug: "tone-tweakers",
    regionId: "east-coast",
    url: "https://tonetweakers.com/",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 70,
    noiseScore: 10,
    testQuery: "synth",
    notes: "Vintage synth and recording studio gear specialist. Live Shopify parser returns product cards; many items require contact for price.",
  },
  {
    id: "pro-audio-star",
    name: "ProAudioStar",
    slug: "pro-audio-star",
    regionId: "east-coast",
    url: "https://www.proaudiostar.com/catalogsearch/result/?q=synth",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 62,
    noiseScore: 36,
    testQuery: "synth",
    notes: "Brooklyn-based online retailer for musical instruments, pro audio, and DJ gear. Wired as Search Assist first.",
  },
  {
    id: "robotspeak",
    name: "Robot Speak",
    slug: "robotspeak",
    regionId: "bay-area",
    url: "https://robotspeak.com/collections/used-gear",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 72,
    noiseScore: 12,
    testQuery: "synth",
    notes: "SF synth shop. Live Shopify search connector returns synths, drum machines, Eurorack, standalone devices, and used gear.",
  },
  {
    id: "mission-synths",
    name: "Mission Synths",
    slug: "mission-synths",
    regionId: "bay-area",
    url: "https://www.missionsynths.com/collections/pre-owned",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 74,
    noiseScore: 14,
    testQuery: "synth",
    notes: "Mission District electronic music hardware shop. Live Shopify search connector filters out classes, records, and merch.",
  },
  {
    id: "starving-musician",
    name: "The Starving Musician",
    slug: "starving-musician",
    regionId: "bay-area",
    url: "https://starvingmusician.com/keyboards/keyboards",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 68,
    noiseScore: 24,
    testQuery: "synth",
    notes: "Independent used/new shop serving Santa Clara and Santa Cruz. Live HTML parser returns cards from the site search.",
  },
  {
    id: "bananas-at-large",
    name: "Bananas at Large",
    slug: "bananas-at-large",
    regionId: "bay-area",
    url: "https://www.bananas.com",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 70,
    noiseScore: 22,
    testQuery: "synth",
    notes: "Marin independent music/pro-audio shop with new, used, and open-box inventory. Live Shopify search connector.",
  },
  {
    id: "gelb-music",
    name: "Gelb Music",
    slug: "gelb-music",
    regionId: "bay-area",
    url: "https://gelbmusic.com/keyboards/keyboard-synthesizer/",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 68,
    noiseScore: 26,
    testQuery: "synth",
    notes: "Redwood City independent shop with keyboard synthesizer and Reverb inventory. Live BigCommerce-style parser returns product cards.",
  },
  {
    id: "facebook-marketplace",
    name: "Facebook Marketplace Musical Instruments",
    slug: "facebook-marketplace",
    regionId: "bay-area",
    url: "https://www.facebook.com/marketplace/category/instruments/",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.CANDIDATE,
    reliabilityScore: 40,
    noiseScore: 45,
    testQuery: "synth",
    notes: "High signal, but should remain manual/user-assisted until official access is clear.",
  },
  {
    id: "offerup",
    name: "OfferUp",
    slug: "offerup",
    regionId: "bay-area",
    url: "https://offerup.com/search?q=synth",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.CANDIDATE,
    reliabilityScore: 45,
    noiseScore: 50,
    testQuery: "synth",
    notes: "Local signal, app-first friction; manual/user-assisted first.",
  },
];

export function getSourceById(sourceId) {
  return SOURCE_REGISTRY.find((source) => source.id === sourceId) || null;
}

export function getSourcesByRegion(regionId) {
  return SOURCE_REGISTRY.filter((source) => source.regionId === regionId);
}

export function getCheckableSources({ includeCandidates = false } = {}) {
  return SOURCE_REGISTRY.filter((source) => {
    if (source.status === SOURCE_STATUSES.PAUSED || source.status === SOURCE_STATUSES.BROKEN) return false;
    if (source.accessType === SOURCE_ACCESS_TYPES.MANUAL) return false;
    if (!includeCandidates && source.status === SOURCE_STATUSES.CANDIDATE) return false;
    return true;
  });
}
