export const SOURCE_ACCESS_TYPES = {
  API: "api",
  SCRAPE: "scrape",
  BROWSER_ASSISTED: "browser-assisted",
  MANUAL: "manual",
  SEARCH_URL: "search-url",
};

export const SOURCE_STATUSES = {
  ACTIVE: "active",
  TESTING: "testing",
  BROKEN: "broken",
  PAUSED: "paused",
  CANDIDATE: "candidate",
};

export const SOURCE_REGISTRY = [
  {
    id: "mercari",
    name: "Mercari Japan",
    slug: "mercari-japan",
    regionId: "japan",
    url: "https://jp.mercari.com",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.BROWSER_ASSISTED,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 72,
    noiseScore: 55,
    testQuery: "Roland Juno 106",
    notes: "High value Japan source; browser automation is slower but currently useful.",
  },
  {
    id: "yahoo-auctions",
    name: "Yahoo Auctions Japan",
    slug: "yahoo-auctions-japan",
    regionId: "japan",
    url: "https://auctions.yahoo.co.jp",
    type: "auction",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 84,
    noiseScore: 45,
    testQuery: "Waldorf",
    notes: "Core Japan auction source.",
  },
  {
    id: "yahoo-fleamarket",
    name: "Yahoo Fleamarket",
    slug: "yahoo-fleamarket",
    regionId: "japan",
    url: "https://paypayfleamarket.yahoo.co.jp",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 78,
    noiseScore: 50,
    testQuery: "Waldorf",
    notes: "Useful Japan marketplace source with occasional noise.",
  },
  {
    id: "rakuma",
    name: "Rakuma",
    slug: "rakuma",
    regionId: "japan",
    url: "https://fril.jp",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 60,
    testQuery: "Waldorf",
    notes: "Useful but can be noisy and thumbnail handling requires proxy support.",
  },
  {
    id: "digimart",
    name: "Digimart",
    slug: "digimart",
    regionId: "japan",
    url: "https://www.digimart.net",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 88,
    noiseScore: 20,
    testQuery: "Sequential Circuits",
    notes: "High signal Japan music gear source.",
  },
  {
    id: "jimoty",
    name: "Jimoty",
    slug: "jimoty",
    regionId: "japan",
    url: "https://jmty.jp/all/sale-inc",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 62,
    noiseScore: 68,
    testQuery: "シンセサイザー",
    notes: "Local classifieds source; likely noisy but useful for local finds.",
  },
  {
    id: "offmall",
    name: "OFFMALL / Hard Off",
    slug: "offmall-hard-off",
    regionId: "japan",
    url: "https://netmall.hardoff.co.jp",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 82,
    noiseScore: 25,
    testQuery: "Roland",
    notes: "Strong used gear network source.",
  },
  {
    id: "five-g",
    name: "Five G",
    slug: "five-g",
    regionId: "japan",
    url: "https://fiveg.net",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 12,
    testQuery: "Oberheim",
    notes: "Low volume but high signal specialist shop.",
  },
  {
    id: "implant4",
    name: "implant4",
    slug: "implant4",
    regionId: "japan",
    url: "https://shop.implant4.com",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.SCRAPE,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 70,
    noiseScore: 12,
    testQuery: "Oberheim",
    notes: "Low volume but high signal specialist shop.",
  },
  {
    id: "reverb",
    name: "Reverb Japan",
    slug: "reverb-japan",
    regionId: "japan",
    url: "https://reverb.com",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.ACTIVE,
    reliabilityScore: 86,
    noiseScore: 22,
    testQuery: "Oberheim",
    notes: "Currently queried with Japan country filter.",
  },
  {
    id: "reverb-us",
    name: "Reverb US",
    slug: "reverb-us",
    regionId: "bay-area",
    url: "https://reverb.com/marketplace?query=synth",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 86,
    noiseScore: 25,
    testQuery: "synth",
    notes: "Recommended first live Bay Area/US connector.",
  },
  {
    id: "ebay-us",
    name: "eBay Synthesizers",
    slug: "ebay-us",
    regionId: "bay-area",
    url: "https://www.ebay.com/sch/i.html?_nkw=synthesizer",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.API,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 78,
    noiseScore: 60,
    testQuery: "synthesizer",
    notes: "Good future API connector, but likely noisy.",
  },
  {
    id: "craigslist-sfbay",
    name: "Craigslist SF Bay Area",
    slug: "craigslist-sfbay",
    regionId: "bay-area",
    url: "https://sfbay.craigslist.org/search/msa?query=synth",
    type: "classifieds",
    accessType: SOURCE_ACCESS_TYPES.SEARCH_URL,
    status: SOURCE_STATUSES.TESTING,
    reliabilityScore: 60,
    noiseScore: 45,
    testQuery: "synth",
    notes: "Manual/search-link first until safe access path is confirmed.",
  },
  {
    id: "facebook-marketplace",
    name: "Facebook Marketplace Musical Instruments",
    slug: "facebook-marketplace",
    regionId: "bay-area",
    url: "https://www.facebook.com/marketplace/category/instruments/",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.CANDIDATE,
    reliabilityScore: 40,
    noiseScore: 45,
    testQuery: "synth",
    notes: "High signal, but should remain manual/user-assisted until official access is clear.",
  },
  {
    id: "offerup",
    name: "OfferUp",
    slug: "offerup",
    regionId: "bay-area",
    url: "https://offerup.com/search?q=synth",
    type: "marketplace",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.CANDIDATE,
    reliabilityScore: 45,
    noiseScore: 50,
    testQuery: "synth",
    notes: "Local signal, app-first friction; manual/user-assisted first.",
  },
  {
    id: "robotspeak",
    name: "Robot Speak",
    slug: "robotspeak",
    regionId: "bay-area",
    url: "https://robotspeak.com/collections/used-gear",
    type: "shop",
    accessType: SOURCE_ACCESS_TYPES.MANUAL,
    status: SOURCE_STATUSES.CANDIDATE,
    reliabilityScore: 55,
    noiseScore: 10,
    testQuery: "synth",
    notes: "Key SF synth shop candidate.",
  },
];

export function getSourceById(sourceId) {
  return SOURCE_REGISTRY.find((source) => source.id === sourceId) || null;
}

export function getSourcesByRegion(regionId) {
  return SOURCE_REGISTRY.filter((source) => source.regionId === regionId);
}

export function getCheckableSources({ includeCandidates = false } = {}) {
  return SOURCE_REGISTRY.filter((source) => {
    if (source.status === SOURCE_STATUSES.PAUSED || source.status === SOURCE_STATUSES.BROKEN) return false;
    if (!includeCandidates && source.status === SOURCE_STATUSES.CANDIDATE) return false;
    return true;
  });
}
